// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.15/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/Error ../../../../../../core/Logger ../../../../../../core/mathUtils ../../../../../../core/mathUtils ../../../../../../core/maybe ../../../../../../core/screenUtils ../../../../engine ../../color ../../definitions ../../enums ../../number ../../WGLDisplayRecord ../../collisions/Metric ../../materialKey/MaterialKey ./segmentUtils ./WGLTextTemplate".split(" "),function(B,y,G,H,I,C,w,p,J,z,D,K,L,k,M,E,x,F,
N){Object.defineProperty(y,"__esModule",{value:!0});var O=I.getLogger("esri.views.2d.engine.webgl.WGLLabelTemplate");y.isMapAligned=function(g){switch(g){case "above-along":case "below-along":case "center-along":return 1;default:return 0}};var P=function(g){var e=new Map;return function(a){e.has(a)||e.set(a,g(a));return e.get(a)}}(function(g){var e=0;if(0===g)return Infinity;for(;!(g%2);)e++,g/=2;return e}),A=function(g,e){return k.i1616to32(2*Math.round(8*g),2*Math.round(8*e))};B=function(g){function e(a,
d,c,b){var f=g.call(this,a,c.font.size,c.haloSize||0,c.color&&D.premultiplyAlphaRGBA(c.color)||0,c.haloColor&&D.premultiplyAlphaRGBA(c.haloColor)||0,c.horizontalAlignment,c.verticalAlignment,c.font.decoration,!1,c.angle||0,c.xoffset,c.yoffset,c.id,c.lineWidth,c.lineHeight)||this;f._outLineLabelAngle=0;f._refPlacementPadding=0;f._refPlacementDirX=0;f._refPlacementDirY=0;f.geometryType=L.WGLGeometryType.LABEL;var m;m=!!d.minScale&&b.scaleToZoom(d.minScale)||0;m=C.clamp(m,0,25.5);b=!!d.maxScale&&b.scaleToZoom(d.maxScale)||
255;b=C.clamp(b,0,25.5);var h=z.alignmentUtils.getAlignmentFromPlacement(d.labelPlacement),e=h[1];f._xAlignD=h[0];f._yAlignD=e;f._minZoom=m;f._maxZoom=b;f._refPlacementPadding=J.pt2px(c.haloSize)+K.TEXT_PLACEMENT_PADDING;a=x.LabelMaterialKey.load(x.createMaterialKey(f.geometryType,a,!1,d));a.sdf=!0;f._materialKey=a.data;return f}G(e,g);e.fromLabelClass=function(a,d,c){if("center-along"===d.labelPlacement){var b=d.symbol;b.xoffset=0;b.yoffset=0;b.angle=0;b.font.decoration="none"}return new e(a,d,d.symbol,
c)};Object.defineProperty(e.prototype,"_shapedBox",{get:function(){return p.unwrap(this._shapingInfo).bounds},enumerable:!0,configurable:!0});e.prototype.bindReferenceTemplate=function(a){var d=z.alignmentUtils.getXDirection(this._xAlignD),c=z.alignmentUtils.getYDirection(this._yAlignD);if(p.isNone(a))this._refSymbolAndPlacementOffset=k.i8888to32(0,0,Math.floor(127*d+127),Math.floor(127*c+127));else{if("circle"===a.boundsType&&(d||c))var b=Math.sqrt(d*d+c*c),d=d/b,c=c/b;a=Math.max(a.height,a.width)+
Math.max(a.xOffset,a.yOffset);this._refSymbolAndPlacementOffset=k.i8888to32(4*this._refPlacementPadding,a,Math.floor(127*d+127),Math.floor(127*c+127));this._referenceSize=a;this._refPlacementDirX=d;this._refPlacementDirY=c}};e.prototype.writeMesh=function(a,d,c,b,f,e,h){if(!p.isNone(this._shapingInfo))switch(this.current={outRecords:a,outVecs:d,outMetrics:h,inId:b,inShaping:this._shapingInfo,zoomLevel:e},c){case "esriGeometryPolyline":return this._placeLineLabels(f.geometry);case "esriGeometryPoint":return this._placePointLabels(f.geometry);
case "esriGeometryPolygon":return this._placePointLabels(f.centroid);default:a="Geometry of type "+c+" is not supported",void 0===a&&(a="mapview-labeling"),O.error(H(a,"mapview-labeling"))}};e.prototype._isVisible=function(a,d){var c=Math.floor(10*this.current.zoomLevel);return Math.floor(10*a)<=c&&c<=Math.floor(10*d)};e.prototype._placePointLabels=function(a){var d=this.current;this._writeGlyphs(d.outRecords,d.outVecs,d.inId,a,d.outMetrics)};e.prototype._placeLineLabels=function(a){a=F.smoothPaths(a.paths,
this.current.inShaping.bounds.width);for(var d=this._placeSubdivGlyphs.bind(this),c=(this._shapedBox.width+128)/4,b=0;b<a.length;b++)F.pathDivide(a[b],c,d)};e.prototype._placeSubdivGlyphs=function(a,d,c,b){var f=P(d);c=w.log2(Math.min(c,b-c)/(4+this._shapedBox.width/4/2));f=Math.max(this._minZoom,this.current.zoomLevel+2-(0===d?c:Math.min(f,c)));c=this._shapedBox.width/2*Math.pow(2,this.current.zoomLevel-f);this.current.inShaping.isMultiline?0===d&&this._placeStraight(a,f):this._placeCurved(a,f,c)};
e.prototype._placeStraight=function(a,d){var c=this.current;this._writeGlyphs(c.outRecords,c.outVecs,c.inId,a,c.outMetrics,d)};e.prototype._placeCurved=function(a,d,c){var b=new E.default(this.current.inId,{from:this.current.outRecords.length,count:-1},a.x,a.y,d),f=a.clone(),e=(180/Math.PI*a.angle+180)%360;this._outLineLabelAngle=Math.round(180/Math.PI*a.angle%360*(254/360));this._placeFirst(f,b,d,1);this._placeBack(a,f,b,d,c,1);this._placeForward(a,f,b,d,c,1);this._outLineLabelAngle=Math.round(254/
360*e);this._placeFirst(f,b,d,0);this._placeBack(a,f,b,d,c,0);this._placeForward(a,f,b,d,c,0);b.range.count=this.current.outRecords.length-b.range.from;b.bounds&&this.current.outMetrics.push(b)};e.prototype._placeBack=function(a,d,c,b,f,e){var h=a.clone();for(a=a.backwardLength+0;h.prev()&&!(a>=f);)this._placeOnSegment(h,d,c,a,b,-1,e),a+=h.length+0};e.prototype._placeForward=function(a,d,c,b,f,e){var h=a.clone();for(a=a.remainingLength+0;h.next()&&!(a>=f);)this._placeOnSegment(h,d,c,a,b,1,e),a+=h.length+
0};e.prototype._placeFirst=function(a,d,c,b){for(var f=this.current.inShaping,e=f.glyphs,h=this.current.zoomLevel,g=this.current,Q=g.outRecords,t=g.outVecs,g=g.inId,r=A(a.x,a.y),u=0;u<e.length;u++){var l=e[u],q=l.x>f.bounds.x?b:1-b,q=Math.max(0,h+w.log2(Math.abs(l.x+l.width/2-f.bounds.x)/(q*a.remainingLength+(1-q)*a.backwardLength+0))),q=Math.max(c,q);l.maxZoom=25;l.angle=a.angle+(1-b)*Math.PI;l.minZoom=q;this._writeGlyph(Q,t,l,g,r);b&&this._isVisible(l.minZoom,l.maxZoom)&&d.add(l.bounds,0,0)}};e.prototype._placeOnSegment=
function(a,d,c,b,f,e,h){for(var g=this.current.inShaping.glyphs,m=this.current,t=m.outRecords,r=m.outVecs,m=m.inId,u=this.current.inShaping,l=this.current.zoomLevel,q=A(a.x+a.dx/a.length*-e*b,a.y+a.dy/a.length*-e*b),k=0;k<g.length;k++){var n=g[k],v=n.x>u.bounds.x?h:1-h;if(v&&1===e||!v&&-1===e){var p=Math.abs(n.x+n.width/2-u.bounds.x),v=Math.max(0,l+w.log2(p/b)-.1),p=Math.max(f,l+w.log2(p/(b+a.length+0)));0!==v&&(n.angle=a.angle+(1-h)*Math.PI,n.minZoom=p,n.maxZoom=v,this._writeGlyph(t,r,n,m,q),h&&
this._isVisible(n.minZoom,n.maxZoom)&&c.add(n.bounds,a.x-d.x,a.y-d.y))}}};e.prototype._writeGlyphs=function(a,d,c,b,e,g){void 0===g&&(g=this._minZoom);var f=this._shapingInfo;if(!(p.isNone(f)||0>b.x||512<=b.x||0>b.y||512<=b.y)){var m=A(b.x,b.y);b=new E.default(c,{from:a.length,count:-1},b.x,b.y,g);for(var k=0,t=f.glyphs;k<t.length;k++){var r=t[k];r.minZoom=g;r.maxZoom=this._maxZoom;this._writeGlyph(a,d,r,c,m)}b.range.count=a.length-b.range.from;b.bounds=f.boundsT;a=x.LabelMaterialKey.load(this._materialKey);
b.setPlacementOffset(a.vvSizeFieldStops||a.vvSizeMinMaxValue||a.vvSizeScaleStops||a.vvSizeUnitValue,this._referenceSize,this._refPlacementPadding,this._refPlacementDirX,this._refPlacementDirY);e.push(b)}};e.prototype._writeGlyph=function(a,d,c,b,e){var f=x.MaterialKeyBase.load(this._materialKey),h=new M(b,this.geometryType,f.data,0,0);f.textureBinding=c.textureBinding;h.materialKey=f.data;h.indexFrom=d.indexVector.length;h.indexCount=this._writeIndices(d);h.vertexFrom=d.getVector("geometry").vertexCount;
h.vertexCount=this._writeVertex(d,b,e,c);a.push(h)};e.prototype._writeVertexCommon=function(a,d,c,b){var e=this._color,g=this._haloColor,h=k.i8888to32(0,0,this._size,this._haloSize);b=k.i8888to32(Math.floor(10*Math.max(b.minZoom,this._minZoom)),Math.floor(10*Math.min(b.maxZoom,this._maxZoom)),this._outLineLabelAngle,0);a.push(c);a.push(d);a.push(e);a.push(g);a.push(h);a.push(this._refSymbolAndPlacementOffset);a.push(b)};return e}(N.default);y.default=B});